### ISSUE TITLE
Failed to install ONL on EdgeCore 5610-52

### ISSUE THREAD

**Issue by krevedkoman** [opennetworklinux/ONL#204]
I have EdgeCore 5610-52X-O-AC-F, i need to install ONL. but i have problems.

```
Launching ONL installer
Extracting from /tmp/sfx-WL6Z1g/onie-installer.zip: preinstall.sh ...
Archive:  /tmp/sfx-WL6Z1g/onie-installer.zip
  inflating: preinstall.sh
Invoking pre-install actions
Hello from preinstall
Chroot is /tmp/sfx-WL6Z1g/initrd-V4Sa6r
Traceback (most recent call last):
  File "/usr/bin/onl-install", line 6, in <module>
    import onl.install.App
  File "/usr/lib/python2.7/dist-packages/onl/install/App.py", line 20, in <module>
    from ShellApp import OnieBootContext
  File "/usr/lib/python2.7/dist-packages/onl/install/ShellApp.py", line 18, in <module>
    import onl.platform.current
  File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 43, in <module>
    OnlPlatform = import_subsystem_platform_class()
  File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 38, in import_subsystem_platform_class
    m = importlib.import_module('%s.platform.%s' % (subsystem, platform_module))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named powerpc_as5610_52x
Install failed.

```

If i change this file /etc.machine.conf

```
ONIE:/ # vi /etc/machine.conf
onie_version=1.6.1
onie_vendor_id=259
onie_platform=powerpc-accton-as5610-52x-r0
onie_machine=accton_5610_52x
onie_machine_rev=0
onie_arch=powerpc
```

i have this problem:

```
Launching ONL installer
Extracting from /tmp/sfx-OWABo0/onie-installer.zip: preinstall.sh ...
Archive:  /tmp/sfx-OWABo0/onie-installer.zip
  inflating: preinstall.sh
Invoking pre-install actions
Hello from preinstall
Chroot is /tmp/sfx-OWABo0/initrd-uqZex9
getting installer configuration
ONL Installer @ONLVERSION@
ONL installer running under ONIE.
Detected platform powerpc-accton-as5610-52x-r0
trying a U-Boot based installer
using proxy GRUB
+ /usr/sbin/fw_setenv --help
loading plugins from /tmp/sfx-OWABo0/plugin-KlvIgB.py
/tmp/sfx-OWABo0/plugin-KlvIgB.py: found plugin Plugin
loading plugins from /tmp/sfx-OWABo0/plugin-2wiAVS.py
/tmp/sfx-OWABo0/plugin-2wiAVS.py: found plugin Plugin
loading plugins from /usr/lib/python2.7/dist-packages/onl/install/plugins/__init__.py
running plugins: preinstall
hello from preinstall plugin
disk /dev/sda is already msdos
Installing to /dev/sda
found msdos partitions (bsz 512, lbsz 512)
found a disk with 3911680 blocks
examining /dev/sda part 1
deleting this part
examining /dev/sda part 2
deleting this part
installer failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/onl/install/App.py", line 212, in runLocalOrChroot
    code = self.installer.run()
  File "/usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py", line 1014, in run
    return self.installUboot()
  File "/usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py", line 960, in installUboot
    code = self.deletePartitions()
  File "/usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py", line 227, in deletePartitions
    self.partedDisk.removePartition(part)
  File "/usr/lib/python2.7/site-packages/parted/decorators.py", line 42, in new
    ret = fn(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/parted/disk.py", line 268, in removePartition
    if self.__disk.remove_partition(partition.getPedPartition()):
PartitionException: Attempting to remove an extended partition that still contains logical partitions
re-attaching to tty
entering Python debugger (installer_debug=1)
/usr/lib/python2.7/site-packages/parted/disk.py(268)removePartition()
if self.__disk.remove_partition(partition.getPedPartition()):
(Pdb)
```

and stop....

Please help me.

**Comment by sonoble** [comment]
Hi,

Are you using the latest version from the opennetlinux.org site or one
that you built?

Looking at the AS5610 that is in the the regression/ci testbed I see the
following machine.conf

ONIE:/ # cat /etc/machine.conf
onie_version=2014.11.00.03
onie_vendor_id=259
onie_platform=powerpc-accton_as5610_52x-r0
onie_machine=accton_as5610_52x
onie_machine_rev=0
onie_arch=powerpc
onie_config_version=0
onie_build_date="2015-01-21T17:38+0800"
onie_partition_type=
onie_kernel_version=3.2.35

You should not need to change the _ to -, we do that automatically.

Installing the installed debian 8 version from the site I get:

Launching ONL installer
Extracting from /tmp/sfx-Cei5fl/onie-installer.zip: preinstall.sh ...
Archive:  /tmp/sfx-Cei5fl/onie-installer.zip
  inflating: preinstall.sh
Invoking pre-install actions
Hello from preinstall
Chroot is /tmp/sfx-Cei5fl/initrd-bn5bFK
getting installer configuration
ONL Installer @ONLVERSION@
ONL installer running under ONIE.
Detected platform powerpc-accton-as5610-52x-r0
trying a U-Boot based installer
using proxy GRUB
+ /usr/sbin/fw_setenv --help
loading plugins from /tmp/sfx-Cei5fl/plugin-8ccu1T.py
/tmp/sfx-Cei5fl/plugin-8ccu1T.py: found plugin Plugin
loading plugins from /tmp/sfx-Cei5fl/plugin-DYZ2aR.py
/tmp/sfx-Cei5fl/plugin-DYZ2aR.py: found plugin Plugin
loading plugins from
/usr/lib/python2.7/dist-packages/onl/install/plugins/__init__.py
running plugins: preinstall
hello from preinstall plugin
disk /dev/sda is already msdos
Installing to /dev/sda
found msdos partitions (bsz 512, lbsz 512)
found a disk with 3911680 blocks
examining /dev/sda part 1
deleting this part
examining /dev/sda part 2
deleting this part
examining /dev/sda part 3
deleting this part
examining /dev/sda part 4
deleting this part
+ partprobe /dev/sda
no partitions, starting at block 1
next usable block is None
Allocating 262144 sectors for ONL-BOOT
+ partprobe /dev/sda
Formatting /dev/sda1 (ONL-BOOT) as ext2
+ mkfs.ext2 -v -L ONL-BOOT /dev/sda1
mke2fs 1.42.7 (21-Jan-2013)

and the install finishes without issue.

**Comment by krevedkoman** [comment]
Hi, i use both methods (my build and latest version  from the opennetlinux.org site).
I'm update ONIE
`ONIE:/ # cat /etc/machine.conf
onie_version=2016.08.00.02
onie_vendor_id=259
onie_platform=powerpc-accton_as5610_52x-r0
onie_machine=accton_as5610_52x
onie_machine_rev=0
onie_arch=powerpc
onie_config_version=0
onie_build_date="2016-09-13T15:16+0800"
onie_partition_type=
onie_kernel_version=3.2.69
onie_firmware=
onie_switch_asic=bcm
onie_skip_ethmgmt_macs=no
`

but i still getting an error

`Info: Fetching tftp://192.168.3.1/ONL ...
ONL                  100% |*******************************|   130M  0:00:00 ETA
ONIE: Executing installer: tftp://192.168.3.1/ONL
installer: computing checksum of original archive
installer: checksum is OK
installer: extracting pad
1+0 records in
1+0 records out
512 bytes (512B) copied, 0.000070 seconds, 7.0MB/s
installer: copying file before resetting pad
installer: resetting pad
1+0 records in
1+0 records out
512 bytes (512B) copied, 0.000076 seconds, 6.4MB/s
installer: extracting shar into /tmp/sfx-DO0eja
installer: invoking installer installer.sh
Found installer tmpfs on /tmp/sfx-DO0eja (/tmp) using opts rw,noatime
Resizing tmpfs /tmp to 1048576k
Unpacking ONL installer files...
Extracting from /tmp/sfx-DO0eja/onie-installer.zip: onl-loader-fit.itb ...
Archive:  /tmp/sfx-DO0eja/onie-installer.zip
  inflating: onl-loader-fit.itb
Extracting initrd to /tmp/sfx-DO0eja/initrd-VPEkBg
1+1 records in
1+1 records out
9257200 bytes (8.8MB) copied, 0.042459 seconds, 207.9MB/s
0+0 records in
0+0 records out
0 bytes (0B) copied, 0.000065 seconds, 0B/s
50786 blocks
gzip: corrupted data
Setting up /dev
Setting up /run
Setting up mounts
Launching ONL installer
Extracting from /tmp/sfx-DO0eja/onie-installer.zip: preinstall.sh ...
Archive:  /tmp/sfx-DO0eja/onie-installer.zip
  inflating: preinstall.sh
Invoking pre-install actions
Hello from preinstall
Chroot is /tmp/sfx-DO0eja/initrd-VPEkBg
getting installer configuration
ONL Installer @ONLVERSION@
ONL installer running under ONIE.
Detected platform powerpc-accton-as5610-52x-r0
trying a U-Boot based installer
using proxy GRUB
+ /usr/sbin/fw_setenv --help
loading plugins from /tmp/sfx-DO0eja/plugin-ZqxpnG.py
/tmp/sfx-DO0eja/plugin-ZqxpnG.py: found plugin Plugin
loading plugins from /tmp/sfx-DO0eja/plugin-OyPwtw.py
/tmp/sfx-DO0eja/plugin-OyPwtw.py: found plugin Plugin
loading plugins from /usr/lib/python2.7/dist-packages/onl/install/plugins/__init                 __.py
running plugins: preinstall
hello from preinstall plugin
disk /dev/sda is already msdos
Installing to /dev/sda
found msdos partitions (bsz 512, lbsz 512)
found a disk with 3911680 blocks
examining /dev/sda part 1
deleting this part
examining /dev/sda part 2
deleting this part
installer failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/onl/install/App.py", line 212, in runLo                 calOrChroot
    code = self.installer.run()
  File "/usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py", line 1014,                  in run
    return self.installUboot()
  File "/usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py", line 960,                  in installUboot
    code = self.deletePartitions()
  File "/usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py", line 227,                  in deletePartitions
    self.partedDisk.removePartition(part)
  File "/usr/lib/python2.7/site-packages/parted/decorators.py", line 42, in new
    ret = fn(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/parted/disk.py", line 268, in removePar                 tition
    if self.__disk.remove_partition(partition.getPedPartition()):
PartitionException: Attempting to remove an extended partition that still contai                 ns logical partitions
re-attaching to tty
entering Python debugger (installer_debug=1)
> /usr/lib/python2.7/site-packages/parted/disk.py(268)removePartition()
-> if self.__disk.remove_partition(partition.getPedPartition()):
(Pdb)
`

**Comment by sonoble** [comment]
Hi, 
Can you check how big the disk is? I am wondering if we have a disk size issue.   Also, if possible run onie uninstall before the installation to make sure the system is in a clean state.

**Comment by krevedkoman** [comment]
```
ONIE:/ # df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                    10.0M     16.0K     10.0M   0% /run
tmpfs                    10.0M         0     10.0M   0% /run/lock
tmpfs                  1012.8M         0   1012.8M   0% /tmp
tmpfs                  1012.8M         0   1012.8M   0% /var/tmp
tmpfs                  1012.8M         0   1012.8M   0% /run/shm

```

**Comment by sonoble** [comment]
You appear to only have 2G of flash, which will fail for the installed image. Are you using the swi installer or the installed installer?

**Comment by krevedkoman** [comment]
i use installed installer.

after run command "onie-uninstaller" i have this:
```
ONIE:/ # onie-nos-install tftp://192.168.3.1/ONL
discover: Rescue mode detected. No discover stopped.
Info: Fetching tftp://192.168.3.1/ONL ...

ONL                  100% |*******************************|   130M  0:00:00 ETA
ONIE: Executing installer: tftp://192.168.3.1/ONL
installer: computing checksum of original archive
installer: checksum is OK
installer: extracting pad
1+0 records in
1+0 records out
512 bytes (512B) copied, 0.000070 seconds, 7.0MB/s
installer: copying file before resetting pad
installer: resetting pad
1+0 records in
1+0 records out
512 bytes (512B) copied, 0.000055 seconds, 8.9MB/s
installer: extracting shar into /tmp/sfx-jBfejL
installer: invoking installer installer.sh
Found installer tmpfs on /tmp/sfx-jBfejL (/tmp) using opts rw,noatime
Resizing tmpfs /tmp to 1048576k
Unpacking ONL installer files...
Extracting from /tmp/sfx-jBfejL/onie-installer.zip: onl-loader-fit.itb ...
Archive:  /tmp/sfx-jBfejL/onie-installer.zip
  inflating: onl-loader-fit.itb
Extracting initrd to /tmp/sfx-jBfejL/initrd-ezxwR6
1+1 records in
1+1 records out
9257200 bytes (8.8MB) copied, 0.042424 seconds, 208.1MB/s
0+0 records in
0+0 records out
0 bytes (0B) copied, 0.000085 seconds, 0B/s
50786 blocks
gzip: corrupted data
Setting up /dev
Setting up /run
Setting up mounts
Launching ONL installer
Extracting from /tmp/sfx-jBfejL/onie-installer.zip: preinstall.sh ...
Archive:  /tmp/sfx-jBfejL/onie-installer.zip
  inflating: preinstall.sh
Invoking pre-install actions
Hello from preinstall
Chroot is /tmp/sfx-jBfejL/initrd-ezxwR6
getting installer configuration
ONL Installer @ONLVERSION@
ONL installer running under ONIE.
Detected platform powerpc-accton-as5610-52x-r0
trying a U-Boot based installer
using proxy GRUB
+ /usr/sbin/fw_setenv --help
loading plugins from /tmp/sfx-jBfejL/plugin-zgo5pR.py
/tmp/sfx-jBfejL/plugin-zgo5pR.py: found plugin Plugin
loading plugins from /tmp/sfx-jBfejL/plugin-NghQh8.py
/tmp/sfx-jBfejL/plugin-NghQh8.py: found plugin Plugin
loading plugins from /usr/lib/python2.7/dist-packages/onl/install/plugins/__init__.py
running plugins: preinstall
hello from preinstall plugin
disk /dev/sda is already msdos
Installing to /dev/sda
found msdos partitions (bsz 512, lbsz 512)
found a disk with 3911680 blocks
no partitions, starting at block 1
next usable block is None
Allocating 262144 sectors for ONL-BOOT
+ partprobe /dev/sda
Formatting /dev/sda1 (ONL-BOOT) as ext2
+ mkfs.ext2 -v -L ONL-BOOT /dev/sda1
mke2fs 1.42.7 (21-Jan-2013)
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/sda1 is mounted.
fs_types for mke2fs.conf resolution: 'ext2', 'small'
Filesystem label=ONL-BOOT
OS type: Linux
Block size=1024 (log=0)
Fragment size=1024 (log=0)
Stride=0 blocks, Stripe width=0 blocks
32512 inodes, 130048 blocks
6502 blocks (5.00%) reserved for the super user
First data block=1
Maximum filesystem blocks=67371008
16 block groups
8192 blocks per group, 8192 fragments per group
2032 inodes per group
Superblock backups stored on blocks:
        8193, 24577, 40961, 57345, 73729

Allocating group tables: done
Writing inode tables: done
Writing superblocks and filesystem accounting information: done

Allocating 262144 sectors for ONL-CONFIG
+ partprobe /dev/sda
Formatting /dev/sda2 (ONL-CONFIG) as ext4
+ mkfs.ext4 -v -O ^huge_file -L ONL-CONFIG /dev/sda2
mke2fs 1.42.7 (21-Jan-2013)
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/sda2 is mounted.
fs_types for mke2fs.conf resolution: 'ext4', 'small'
Filesystem label=ONL-CONFIG
OS type: Linux
Block size=1024 (log=0)
Fragment size=1024 (log=0)
Stride=0 blocks, Stripe width=0 blocks
32768 inodes, 131072 blocks
6553 blocks (5.00%) reserved for the super user
First data block=1
Maximum filesystem blocks=67371008
16 block groups
8192 blocks per group, 8192 fragments per group
2048 inodes per group
Superblock backups stored on blocks:
        8193, 24577, 40961, 57345, 73729

Allocating group tables: done
Writing inode tables: done
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

Allocating 1572864 sectors for ONL-IMAGES
+ partprobe /dev/sda
Formatting /dev/sda3 (ONL-IMAGES) as ext4
+ mkfs.ext4 -v -O ^huge_file -L ONL-IMAGES /dev/sda3
mke2fs 1.42.7 (21-Jan-2013)
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/sda3 is mounted.
fs_types for mke2fs.conf resolution: 'ext4'
Filesystem label=ONL-IMAGES
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
49152 inodes, 196608 blocks
9830 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=201326592
6 block groups
32768 blocks per group, 32768 fragments per group
8192 inodes per group
Superblock backups stored on blocks:
        32768, 98304, 163840

Allocating group tables: done
Writing inode tables: done
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

Allocating 1814527 sectors for ONL-DATA
+ partprobe /dev/sda
Formatting /dev/sda4 (ONL-DATA) as ext4
+ mkfs.ext4 -v -O ^huge_file -L ONL-DATA /dev/sda4
mke2fs 1.42.7 (21-Jan-2013)
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/sda4 is mounted.
fs_types for mke2fs.conf resolution: 'ext4'
Filesystem label=ONL-DATA
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
56784 inodes, 226816 blocks
11340 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=234881024
7 block groups
32768 blocks per group, 32768 fragments per group
8112 inodes per group
Superblock backups stored on blocks:
        32768, 98304, 163840

Allocating group tables: done
Writing inode tables: done
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

+ blkid
Installing ONL Software Image (ONL-2.0.0_ONL-OS_2017-03-16.0342-0ba31c9_PPC.swi)...
+ /bin/mkdir /tmp/sfx-jBfejL/mount-41rekL.d
+ mount -v /dev/sda3 /tmp/sfx-jBfejL/mount-41rekL.d
+ unzip -p onie-installer.zip ONL-2.0.0_ONL-OS_2017-03-16.0342-0ba31c9_PPC.swi > /tmp/sfx-jBfejL/mount-41rekL.d/ONL-2.0.0_ONL-OS_2017-03-16.0342-0ba31c9_PPC.swi
+ umount -v /tmp/sfx-jBfejL/mount-41rekL.d
+ /bin/rmdir /tmp/sfx-jBfejL/mount-41rekL.d
Installing the ONL loader from onl-loader-fit.itb...
Installing ONL loader onl-loader-fit.itb --> /dev/sda1:onl-loader-fit.itb...
+ /bin/mkdir /tmp/sfx-jBfejL/mount-bLn6qY.d
+ mount -v /dev/sda1 /tmp/sfx-jBfejL/mount-bLn6qY.d
+ /bin/cp -a /mnt/installer/onl-loader-fit.itb /tmp/sfx-jBfejL/mount-bLn6qY.d/powerpc-accton-as5610-52x-r0.itb
+ umount -v /tmp/sfx-jBfejL/mount-bLn6qY.d
+ /bin/rmdir /tmp/sfx-jBfejL/mount-bLn6qY.d
Installing boot-config to /dev/sda1
+ /bin/mkdir /tmp/sfx-jBfejL/mount-Cs0K3d.d
+ mount -v /dev/sda1 /tmp/sfx-jBfejL/mount-Cs0K3d.d
+ unzip -p onie-installer.zip boot-config > /tmp/sfx-jBfejL/mount-Cs0K3d.d/boot-config
+ umount -v /tmp/sfx-jBfejL/mount-Cs0K3d.d
+ /bin/rmdir /tmp/sfx-jBfejL/mount-Cs0K3d.d
+ /usr/sbin/fw_setenv boot-config-default TkVUREVWPW1hMQpCT09UTU9ERT1JTlNUQUxMRUQKU1dJPWltYWdlczo6bGF0ZXN0Cg==
+ /bin/mkdir /tmp/sfx-jBfejL/mount-h4DTZG.d
+ mount -v /dev/sda2 /tmp/sfx-jBfejL/mount-h4DTZG.d
+ unzip -p onie-installer.zip config/README > /tmp/sfx-jBfejL/mount-h4DTZG.d/README
+ umount -v /tmp/sfx-jBfejL/mount-h4DTZG.d
+ /bin/rmdir /tmp/sfx-jBfejL/mount-h4DTZG.d
syncing block devices
+ sync
+ /usr/sbin/fw_setenv onl_installer_initrd onl-loader-fit.itb:8bb994:118f0a7
Setting ONIE nos_bootcmd to boot ONL
+ /usr/sbin/fw_setenv nos_bootcmd setenv onl_loadaddr 0x10000000; setenv onl_platform powerpc-accton-as5610-52x-r0; setenv onl_itb powerpc-accton-as5610-52x-r0.itb; setenv bootargs console=$consoledev,$baudrate onl_platform=$onl_platform; usb start; ext2load usb 0:1 $onl_loadaddr $onl_itb; bootm $onl_loadaddr#$onl_platform
running plugins: postinstall
hello from postinstall plugin
Install finished.
Invoking post-install actions
Extracting from /tmp/sfx-jBfejL/onie-installer.zip: postinstall.sh ...
+ . /tmp/sfx-jBfejL/postinst-QuTSZG
+ set +x
Archive:  /tmp/sfx-jBfejL/onie-installer.zip
  inflating: postinstall.sh
Hello from postinstall
Chroot is /tmp/sfx-jBfejL/initrd-ezxwR6
Unmounting /tmp/sfx-jBfejL/initrd-ezxwR6/sys
Unmounting /tmp/sfx-jBfejL/initrd-ezxwR6/proc
Unmounting /tmp/sfx-jBfejL/initrd-ezxwR6/mnt/installer
Unmounting /tmp/sfx-jBfejL/initrd-ezxwR6/dev/pts
Remounting /tmp with options rw,noatime,size=50%
Rebooting in 3s
CR, rebooting
Hit CR to continue, CTRL-D or CTRL-C to stop... ONIE: NOS install successful: tftp://192.168.3.1/ONL
ONIE: Rebooting...

```

and......

```
Open Network Linux OS ONL-2.0.0, 2017-03-16.03:42-0ba31c9

localhost login:

```

it's work ! thank you very much )))) !
